let body=document.getElementsByTagName("body");
let div=document.createElement("div");
let txta=document.createElement("a");
let txta2=document.createElement("a");
let txt1=document.createElement("h1");
let txt2=document.createElement("h2");
let txt3=document.createElement("h2");
let txt4=document.createElement("h3");
let txt5=document.createElement("h3");
txta.innerText = "Soy el más grande...";
txt2.innerText = "Curso Web 2020";
txta2.innerText = "Mediano";
txt4.innerText = "Jelou";
txt5.innerText = "Estoy medio chikito :(";
txta.setAttribute("href", "#");
txta2.setAttribute("href", "#");
txta2.setAttribute("class", "a");
txt4.setAttribute("id","rojo");
body[0].appendChild(div);
div.appendChild(txt1);
txt1.appendChild(txta);
div.appendChild(txt2);
div.appendChild(txt3);
txt3.appendChild(txta2);
div.appendChild(txt4);
div.appendChild(txt5);